run:
  timeout: 30s
  issues-exit-code: 1

linters:
  enable-all: true
  disable:
    - bodyclose
    - cyclop
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gci
    - gomnd
    - ireturn
    - nestif
    - nonamedreturns
    - mnd
    - revive
    - testpackage
    - stylecheck
    - varnamelen
